(function(){
    const translations = {
        en: {
            // common
            settings: 'Settings',
            appearance: 'Appearance',
            darkMode: 'Dark mode',
            darkModeDesc: 'Switch between light and dark theme',
            language: 'Language',
            languageDesc: 'Choose your preferred language',
            units: 'Units',
            distanceUnit: 'Distance unit',
            distanceUnitDesc: 'Show distances in kilometers or miles',
            miles: 'miles',
            notifications: 'Notifications',
            pushNotifications: 'Push notifications',
            pushNotificationsDesc: 'Receive notifications about deliveries',
            emailNotifications: 'Email notifications',
            emailNotificationsDesc: 'Get updates via email',
            privacy: 'Privacy',
            locationServices: 'Location services',
            locationServicesDesc: 'Allow app to access your location',
            shareAnalytics: 'Share analytics',
            shareAnalyticsDesc: 'Help improve the app by sharing usage data',
            account: 'Account',
            changeProfilePicture: 'Change profile picture',
            changeProfilePictureDesc: 'Update your avatar',
            signOut: 'Sign out',
            signOutDesc: 'Sign out of your account',
            profilePictureUpdated: 'Profile picture updated!',
            confirmSignOut: 'Are you sure you want to sign out?',
            // usersettings: calendar / non-working days / currency
            calendar: 'Calendar',
            weekStart: 'Week start',
            weekStartDesc: 'Choose the first day of the week',
            sunday: 'Sunday',
            monday: 'Monday',
            saturday: 'Saturday',
            nonWorkingDays: 'Non-working days',
            nonWorkingDaysDesc: 'Mark days as non-working',
            nonWorkingColor: 'Non-working color',
            nonWorkingColorDesc: 'Color for non-working days',
            dayShortSun: 'Sun',
            dayShortMon: 'Mon',
            dayShortTue: 'Tue',
            dayShortWed: 'Wed',
            dayShortThu: 'Thu',
            dayShortFri: 'Fri',
            dayShortSat: 'Sat',
            currency: 'Currency',
            currencyDesc: 'Choose currency for prices',
            currency_EUR: '🇪🇺 EUR',
            currency_USD: '🇺🇸 USD',
            currency_BGN: '🇧🇬 BGN',
            km: 'km',

            // index / app
            hello: 'Hello',
            stores: 'Stores',
            products: 'Products',
            manageProducts: 'Manage products',
            distributedProduct: 'Distributed product',
            makeDelivery: 'Make a delivery',
            chooseStore: 'Choose a store',
            chooseProduct: 'Choose a product',
            setUpStores: 'Set up your stores',
            setUpStore: 'Set up a store',
            storeName: 'Store name',
            storeLocation: 'Store location',
            ownerNames: "Owner/s names",
            addProduct: 'Add a product',
            productName: 'Product name',
            enterStoreName: 'Enter store name',
            enterOwnerNames: 'Enter owner name(s)',
            enterStoreLocation: 'Enter address or search on Google Maps',
            enterProductName: 'Enter product name',
            quantity: 'Quantity',
            shareText: 'Share Text',
            downloadExcel: 'Download Excel',
            noDeliveries: 'No deliveries on this day',
            noStoresMessage: "You haven't set up any stores yet. Set up the stores you distribute to to get started.",
            noProductsMessage: "You haven't set up any products yet. Add the products you distribute to get started.",
            save: 'Save',
            deliverySuccess: 'Delivered',
            editDelivery: 'Edit Delivery',
            deleteDelivery: 'Delete',
            editStore: 'Edit',
            deleteStore: 'Delete',
            editProduct: 'Edit',
            deleteProduct: 'Delete',
            saveChanges: 'Save Changes',
            store: 'Store',
            product: 'Product',
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: 'June',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
            sun: 'Sun',
            mon: 'Mon',
            tue: 'Tue',
            wed: 'Wed',
            thu: 'Thu',
            fri: 'Fri',
            sat: 'Sat',
            gpsTracking: 'GPS Tracking',
            nearbyStores: 'Nearby Stores',
            sortedByDistance: 'Sorted by distance',
            yourLocation: 'Your Location',
            distance: 'Distance',
            nearby: 'NEARBY',
            startGPS: 'Start GPS Tracking',
            stopGPS: 'Stop GPS Tracking',
            loadingGPS: 'Loading GPS...',
            gpsActive: 'GPS Active',
            gpsError: 'GPS Error',
            owner: 'Owner',
            arrived: 'You\'ve arrived at',
            findingLocation: 'Finding your location...',
            closestStoreFound: 'Closest store found',
            continueTo: 'Continue to',
            skip: 'Skip',
            next: 'Next',
            welcome: 'Welcome to ePS!',
            introStep1Title: 'Welcome to ePS',
            introStep1Desc: 'Track your product deliveries efficiently with our app. Let\'s get you set up!',
            introStep2Title: 'Set Up Your Stores',
            introStep2Desc: 'Add the stores you distribute to. Click the Stores card to create your first store.',
            introStep3Title: 'Add Your Products',
            introStep3Desc: 'Create a list of products you deliver. Click the Products card to add them.',
            introStep4Title: 'Make a Delivery',
            introStep4Desc: 'Use the "Make a delivery" button to record each delivery with store and product info.',
            introStep5Title: 'View Reports',
            introStep5Desc: 'Click on any calendar day to view deliveries and export reports as text or Excel.',
            getStarted: 'Get Started',

            // export labels
            price: 'Price',
            total: 'Total',
            sum: 'Sum',

            // misc alerts
            pleaseFillAllFields: 'Please fill in all fields',
            showTutorial: 'Show tutorial',
            storeSavedSuccess: 'Store saved successfully!',
            productSavedSuccess: 'Product saved successfully!',
            storeUpdatedSuccess: 'Store updated successfully!',
            productUpdatedSuccess: 'Product updated successfully!',
            reportCopied: '✓ Report copied to clipboard!',
            reportDownloaded: '✓ Report downloaded!',
            reportDownloadError: 'Failed to generate report',
            enter0ToClose: 'Enter 0 to close',
            gpsModuleNotInitialized: 'GPS module not initialized'
        },
        bg: {
            // usersettings / common
            settings: 'Настройки',
            appearance: 'Външен вид',
            darkMode: 'Тъмен режим',
            darkModeDesc: 'Превключване между светъл и тъмен режим',
            language: 'Език',
            languageDesc: 'Изберете предпочитания език',
            units: 'Мерни единици',
            distanceUnit: 'Единица за разстояние',
            distanceUnitDesc: 'Показване на разстояния в километри или мили',
            miles: 'мили',
            notifications: 'Известия',
            pushNotifications: 'Push известия',
            pushNotificationsDesc: 'Получавайте известия за доставки',
            emailNotifications: 'Имейл известия',
            emailNotificationsDesc: 'Получавайте актуализации по имейл',
            privacy: 'Поверителност',
            locationServices: 'Услуги за местоположение',
            locationServicesDesc: 'Позволяване на приложението да достъпва вашето местоположение',
            shareAnalytics: 'Споделяне на анализи',
            shareAnalyticsDesc: 'Помогнете за подобряване на приложението чрез споделяне на данни за използване',
            account: 'Профил',
            changeProfilePicture: 'Промяна на снимката на профила',
            changeProfilePictureDesc: 'Актуализиране на вашия аватар',
            signOut: 'Изход',
            signOutDesc: 'Излезте от профила си',
            profilePictureUpdated: 'Снимката на профила е актуализирана!',
            confirmSignOut: 'Сигурни ли сте, че искате да излезете?',
            // usersettings: calendar / non-working days / currency
            calendar: 'Календар',
            weekStart: 'Начален ден на седмицата',
            weekStartDesc: 'Изберете първия ден от седмицата',
            sunday: 'Неделя',
            monday: 'Понеделник',
            saturday: 'Събота',
            nonWorkingDays: 'Неработни дни',
            nonWorkingDaysDesc: 'Отбележете дните като неработни',
            nonWorkingColor: 'Цвят за неработни дни',
            nonWorkingColorDesc: 'Цвят за неработни дни',
            dayShortSun: 'Нед',
            dayShortMon: 'Пон',
            dayShortTue: 'Вто',
            dayShortWed: 'Сря',
            dayShortThu: 'Чет',
            dayShortFri: 'Пет',
            dayShortSat: 'Съб',
            currency: 'Валута',
            currencyDesc: 'Изберете валута за цените',
            currency_EUR: '🇪🇺 EUR',
            currency_USD: '🇺🇸 USD',
            currency_BGN: '🇧🇬 BGN',
            km: 'км',

            // index / app
            hello: 'Здравейте',
            stores: 'Магазини',
            products: 'Продукти',
            manageProducts: 'Управление на продукти',
            distributedProduct: 'Разпределена продукция',
            makeDelivery: 'Направи доставка',
            chooseStore: 'Избери магазин',
            chooseProduct: 'Избери продукт',
            setUpStores: 'Настрой магазините си',
            setUpStore: 'Настрой магазин',
            storeName: 'Име на магазина',
            storeLocation: 'Местоположение на магазина',
            ownerNames: 'Имена на собствениците',
            addProduct: 'Добави продукт',
            productName: 'Име на продукт',
            enterStoreName: 'Въведи име на магазина',
            enterOwnerNames: 'Въведи имена на собствениците',
            enterStoreLocation: 'Въведи адрес или потърси в Google Maps',
            enterProductName: 'Въведи име на продукта',
            quantity: 'Количество',
            shareText: 'Сподели текст',
            downloadExcel: 'Изтегли Excel',
            noDeliveries: 'Няма доставки този ден',
            noStoresMessage: 'Все още не си настроил магазини. Настрой магазините, на които разпределяш, за да започнеш.',
            noProductsMessage: 'Все още не си настроил продукти. Добави продуктите, които разпределяш, за да започнеш.',
            save: 'Запази',
            deliverySuccess: 'Доставено',
            editDelivery: 'Редактирай доставка',
            deleteDelivery: 'Изтрий',
            editStore: 'Редактирай',
            deleteStore: 'Изтрий',
            editProduct: 'Редактирай',
            deleteProduct: 'Изтрий',
            saveChanges: 'Запази промени',
            store: 'Магазин',
            product: 'Продукт',
            january: 'Януари',
            february: 'Февруари',
            march: 'Март',
            april: 'Април',
            may: 'Май',
            june: 'Юни',
            july: 'Юли',
            august: 'Август',
            september: 'Септември',
            october: 'Октомври',
            november: 'Ноември',
            december: 'Декември',
            sun: 'Нед',
            mon: 'Пон',
            tue: 'Вто',
            wed: 'Сря',
            thu: 'Чет',
            fri: 'Пет',
            sat: 'Съб',
            gpsTracking: 'GPS проследяване',
            nearbyStores: 'Близки магазини',
            sortedByDistance: 'Сортирано по разстояние',
            yourLocation: 'Вашето местоположение',
            distance: 'Разстояние',
            nearby: 'БЛИЗО',
            startGPS: 'Начни GPS проследяване',
            stopGPS: 'Спри GPS проследяване',
            loadingGPS: 'Зареждане на GPS...',
            gpsActive: 'GPS е активно',
            gpsError: 'GPS грешка',
            owner: 'Собственик',
            arrived: 'Пристигнал(а) си при',
            findingLocation: 'Търсене на местоположение...',
            closestStoreFound: 'Най-близък магазин намерен',
            continueTo: 'Продължи към',
            skip: 'Пропусни',
            next: 'Напред',
            welcome: 'Добре дошли в ePS!',
            introStep1Title: 'Добре дошли в ePS',
            introStep1Desc: 'Проследявайте вашите доставки на продукти ефективно с нашето приложение. Нека да те настроим!',
            introStep2Title: 'Настрой своите магазини',
            introStep2Desc: 'Добави магазините, на които разпределяш. Кликни на картата Магазини, за да създадеш първия си магазин.',
            introStep3Title: 'Добави своите продукти',
            introStep3Desc: 'Създай списък с продуктите, които доставяш. Кликни на картата Продукти, за да ги добавиш.',
            introStep4Title: 'Направи доставка',
            introStep4Desc: 'Използвай бутона "Направи доставка", за да регистрираш всяка доставка с информация за магазина и продукта.',
            introStep5Title: 'Преглед на доклади',
            introStep5Desc: 'Кликни на всеки ден в календара, за да видиш доставките и да експортираш доклади като текст или Excel.',
            getStarted: 'Да започваме',

            // export labels
            price: 'Цена',
            total: 'Общо',
            sum: 'Сума',

            // misc alerts
            pleaseFillAllFields: 'Моля, попълнете всички полета',
            showTutorial: 'Покажи урока',
            storeSavedSuccess: 'Магазинът е запазен успешно!',
            productSavedSuccess: 'Продуктът е запазен успешно!',
            storeUpdatedSuccess: 'Магазинът е актуализиран успешно!',
            productUpdatedSuccess: 'Продуктът е актуализиран успешно!',
            reportCopied: '✓ Докладът е копиран в клипборда!',
            reportDownloaded: '✓ Докладът е изтеглен!',
            reportDownloadError: 'Не може да се генерира доклад',
            enter0ToClose: 'Въведете 0 за да затворите',
            gpsModuleNotInitialized: 'GPS модулът не е инициализиран'
        }
    };

    function getCurrentLanguage() {
        return localStorage.getItem('eps_language') || 'en';
    }

    function setLanguage(lang) {
        localStorage.setItem('eps_language', lang);
        translateDOM();
        window.dispatchEvent(new Event('storage'));
    }

    function t(key) {
        const lang = getCurrentLanguage();
        return (translations[lang] && translations[lang][key]) || (translations.en && translations.en[key]) || '';
    }

    function translateDOM() {
        const lang = getCurrentLanguage();
        const tmap = translations[lang] || translations.en;

        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (tmap[key]) {
                el.textContent = tmap[key];
            }
        });

        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (tmap[key]) el.placeholder = tmap[key];
        });

        document.querySelectorAll('[data-i18n-title]').forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            if (tmap[key]) el.title = tmap[key];
        });
    }

    window.i18n = {
        translations,
        getCurrentLanguage,
        setLanguage,
        t,
        translateDOM
    };

    document.addEventListener('DOMContentLoaded', () => {
        translateDOM();
    });
})();
